POST http://localhost:8080/api/associations
Content-Type: application/json

{
  "nomAssociation": "Pommade",
  "nomResponsable": "Jerome",
  "ville": "Orléans"
}

###

POST http://localhost:8080/api/cagnottes
Authorization: Basic Jerome Pommade
Content-Type: application/json

{
  "nomCagnotte": "Cagnotte pour ARGENT",
  "montantDemandee": 1000,
  "dateFin": "2021-05-30",
  "isActive": true
}
###
POST http://localhost:8080/api/cagnottes/b0391ffe-5b47-4b32-9cad-f840444f99ee
Content-Type: application/json

{
  "nom": "Quetier",
  "prenom": "Thomas",
  "heure": "2021-04-23T19:38:25",
  "montant": 100
}
###
GET http://localhost:8080/api/cagnottes
Authorization: Basic Jerome Pommade
Content-Type: application/json
